// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msrfiyovfhgyzeivrtlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcmZpeW92ZmhneXplaXZydGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjU1OTksImV4cCI6MjA2NzcwMTU5OX0.33r7uOriWmhBowdeTDG7Sgewj2-0Y_vJByUtxirkyoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});